spring:
  profiles:
    active: dev
  application:
    name: "simple-admin"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /admin
  port: 8000
