spring:
  datasource:
    url: jdbc:mysql://192.168.0.104:3306/simple_admin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    ##hikari数据库连接池配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #最小空闲连接数
      minimum-idle: 5
      #最大连接数，默认10
      maximum-pool-size: 12
      #自动提交
      auto-commit: true
      #空闲连接最大存活时间，默认600000（10分钟）
      idle-timeout: 180000
      #连接池名称
      pool-name: Hikaricp
      #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      #数据库连接超时时间,默认30秒，即30000
      connection-timeout: 3000
      #数据库连接测试
      connection-test-query: select 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  check-config-location: true
#  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.anyfork.modules.entity
  type-enums-package: com.anyfork.enums
  executor-type: simple
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #对所有的 resultMap 都进行自动映射
    auto-mapping-behavior: full
    #开启全局懒加载
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    #自动映射，对未知列或者属性进行警告
    auto-mapping-unknown-column-behavior: none
    #关闭mybatis一级缓存
    local-cache-scope: statement
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    db-config:
      #开启数据库表名字下划线
      table-underline: true
      #主键生成策略
      id-type: assign_id
      #逻辑删除字段
      logic-delete-field: deleteFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
anyfork:
  user-name: "小紫念沁"
  enabled: true
  password: "123456"
  encryptor:
    # 对称算法密钥，随机字符串作为密钥即可（有些算法长度有要求，注意）
    password: qmh9MK4KsZY8FnqkJYk8tzgc0H
    # 非对称加密 RSA 公钥私钥
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCEOCMScPeNaJ0DP9N9vd/fXwPGUVnuxeGPpRePXfWuX/X/Yk5IMhwEfYLXictxQk/oAqGnqtDuS/PCL/7mqL+8wFSYnWWErCSkDdT6LjyD07l9dWv+Xj1UTEjP24sEgYA92f4AZyvhsw8I/Bj6a9a30r+kVOGoEZgGMf2c2xK4CQIDAQAB
    privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAIQ4IxJw941onQM/0329399fA8ZRWe7F4Y+lF49d9a5f9f9iTkgyHAR9gteJy3FCT+gCoaeq0O5L88Iv/uaov7zAVJidZYSsJKQN1PouPIPTuX11a/5ePVRMSM/biwSBgD3Z/gBnK+GzDwj8GPpr1rfSv6RU4agRmAYx/ZzbErgJAgMBAAECgYBAlFK9DSQ8k14tWh1oizcvmO71DIMKluhHCvHo+pGnLAOxS0jFBoScxNkFga42kZcJ0U8337zQx5Q1ws+TxdRwHxQO889ZGQH3kOFB0ErUMTgFrTOakZhV0dMWzebkYitNcduSKZ1yfgM5ekF9k3owPIQhUNy8eXjagiLLb9/woQJBALwofOx+fuanQLC1yotFqYAx0XED9EpVPhS/G8mc4dZSNWZ548bIyq3ozP0CoHqriQo/X3NVzIJOU3rhn92fwj0CQQCz5FaeHzSqe1H4bTxzwgR5BUHttxrAPtktwfgCRgaSrZByjFldtP/dGaJmjR2Vzp848WcusJZlSlaLTfndm6W9AkEAoSxlZgctGNKn3Ta7mvU/Lmp+J7rlZU8DcK4LVXYnFXkx+OfsLvkMdE/4V7oKUUnih36lepxCJFSHubjPQf55WQJBAIUa8yxUkreCQAi9avmMGZsiVMH7tgOBfVjqKQQlpD9rxXG8f3Nitd93VD7lM3rhQ9byaBKX/vA7rQWuUK+0t1ECQDTGhLRJFZK4J7UGklTX94pknM/5rO3N/JPkFJcGilbgzkqy0s13D1K+8cR0qTn2DPW8vPoLQpVGuaATTTmMdvg=
    algorithm: PBEWithMD5AndDES